import type { SessionNotes } from "@/lib/session-notes";

// Client-side PDF rendering. jsPDF is ~350 KB, so it is behind a dynamic
// import: the cost is paid only when someone actually downloads notes, and it
// never lands in the main bundle.

type PdfMeta = {
  skillName: string | null;
  teacherName: string;
  learnerName: string;
  scheduledAt: string | null;
  generatedAt: string | null;
};

const MARGIN = 18;
const PAGE_WIDTH = 210; // A4 portrait, mm
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatDate(value: string | null): string {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function safeFileName(skillName: string | null): string {
  const base = (skillName ?? "session").toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return `skillswap-notes-${base.replace(/^-+|-+$/g, "") || "session"}.pdf`;
}

export async function downloadSessionNotesPdf(notes: SessionNotes, meta: PdfMeta): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  let y = MARGIN;

  // Advances the cursor, adding a page whenever the next block would overflow.
  const ensureSpace = (needed: number) => {
    if (y + needed > PAGE_HEIGHT - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const writeParagraph = (text: string, size: number, lineHeight: number) => {
    doc.setFontSize(size);
    for (const line of doc.splitTextToSize(text, CONTENT_WIDTH) as string[]) {
      ensureSpace(lineHeight);
      doc.text(line, MARGIN, y);
      y += lineHeight;
    }
  };

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(meta.skillName ? `${meta.skillName} session notes` : "Session notes", MARGIN, y);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  const subtitle = [
    `${meta.teacherName} taught ${meta.learnerName}`,
    formatDate(meta.scheduledAt),
  ].filter(Boolean);
  for (const line of subtitle) {
    doc.text(line, MARGIN, y);
    y += 5;
  }
  doc.setTextColor(0);
  y += 3;

  doc.setDrawColor(220);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  // ── Summary ───────────────────────────────────────────────────────────────
  if (notes.summary) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    ensureSpace(8);
    doc.text("Summary", MARGIN, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    writeParagraph(notes.summary, 10.5, 5.2);
    y += 4;
  }

  // ── Bulleted sections ─────────────────────────────────────────────────────
  const sections: { title: string; items: string[] }[] = [
    { title: "Key topics", items: notes.keyTopics },
    { title: "Takeaways", items: notes.takeaways },
    { title: "Action items", items: notes.actionItems },
    { title: "Open questions", items: notes.questionsRaised },
  ];

  for (const section of sections) {
    if (!section.items.length) continue;

    ensureSpace(12);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(section.title, MARGIN, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    for (const item of section.items) {
      // Hanging indent so wrapped lines align under the text, not the bullet.
      const lines = doc.splitTextToSize(item, CONTENT_WIDTH - 5) as string[];
      lines.forEach((line, index) => {
        ensureSpace(5.2);
        if (index === 0) doc.text("•", MARGIN, y);
        doc.text(line, MARGIN + 5, y);
        y += 5.2;
      });
    }
    y += 4;
  }

  // ── Footer on every page ──────────────────────────────────────────────────
  const generated = formatDate(meta.generatedAt);
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(
      `Generated by SkillSwap AI${generated ? ` on ${generated}` : ""}. The call recording was deleted after processing.`,
      MARGIN,
      PAGE_HEIGHT - 10,
    );
    doc.text(`${page} / ${pageCount}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: "right" });
  }

  doc.save(safeFileName(meta.skillName));
}
