import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { fetchSessionNotes, type SessionNotesRow } from "@/lib/session-notes";
import { downloadSessionNotesPdf } from "@/lib/session-notes-pdf";
import { Download, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";

type Props = {
  sessionId: string;
  skillName: string | null;
  teacherName: string;
  learnerName: string;
  scheduledAt: string | null;
};

export function SessionNotesPanel({
  sessionId,
  skillName,
  teacherName,
  learnerName,
  scheduledAt,
}: Props) {
  const [row, setRow] = useState<SessionNotesRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    let alive = true;

    void fetchSessionNotes(sessionId).then((result) => {
      if (!alive) return;
      setRow(result);
      setLoading(false);
    });

    // Notes are generated by an Edge Function that can take a minute. Watching
    // the row means a participant sitting on this page sees them appear
    // without a refresh, including the person who did NOT hit record.
    const channel = supabase
      .channel(`session-notes-${sessionId}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "session_notes",
          filter: `session_id=eq.${sessionId}`,
        },
        (msg) => {
          const next = msg.new as SessionNotesRow | undefined;
          if (next?.session_id) setRow(next);
        },
      )
      .subscribe();

    return () => {
      alive = false;
      void supabase.removeChannel(channel);
    };
  }, [sessionId]);

  // Nothing has ever been recorded for this session — stay out of the way.
  if (loading || !row) return null;

  const handleDownload = async () => {
    if (!row.notes) return;
    setDownloading(true);
    try {
      await downloadSessionNotesPdf(row.notes, {
        skillName,
        teacherName,
        learnerName,
        scheduledAt,
        generatedAt: row.generated_at,
      });
    } catch {
      toast.error("Could not build the PDF.");
    } finally {
      setDownloading(false);
    }
  };

  const sections: { title: string; items: string[] }[] = row.notes
    ? [
        { title: "Key topics", items: row.notes.keyTopics },
        { title: "Takeaways", items: row.notes.takeaways },
        { title: "Action items", items: row.notes.actionItems },
        { title: "Open questions", items: row.notes.questionsRaised },
      ].filter((section) => section.items.length > 0)
    : [];

  return (
    // self-start stops the grid row from stretching this card to match the
    // (much taller) left column, which left a large blank gap under the notes.
    <section className="animate-fade-up glass-gradient self-start rounded-3xl border border-white/10 p-5 md:p-6">
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-brand-purple/15">
            <FileText className="h-4 w-4 text-brand-purple" />
          </div>
          <div className="min-w-0">
            <h2 className="text-base font-semibold leading-tight">Session Notes</h2>
            <span className="text-xs text-muted-foreground">Generated from your session.</span>
          </div>
        </div>

        {row.status === "ready" && row.notes ? (
          <Button
            variant="outline"
            size="sm"
            onClick={() => void handleDownload()}
            disabled={downloading}
          >
            {downloading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Download className="h-4 w-4" />
            )}
            Download PDF
          </Button>
        ) : null}
      </div>

      {row.status === "processing" ? (
        <div className="flex items-center gap-3 rounded-xl border border-border/60 px-4 py-3 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Generating notes from the recording. This usually takes under a minute.
        </div>
      ) : null}

      {row.status === "failed" ? (
        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-900 dark:text-amber-100">
          <p className="font-medium">Notes could not be generated.</p>
          <p className="mt-1 opacity-90">
            {row.error ?? "Something went wrong while processing the recording."} You can record
            again on your next call.
          </p>
        </div>
      ) : null}

      {row.status === "ready" && row.notes ? (
        <div className="scroll-slim max-h-[30rem] space-y-4 overflow-y-auto overscroll-contain pr-1.5">
          {row.notes.summary ? (
            <div className="rounded-xl border border-brand-purple/25 bg-brand-purple/[0.06] px-3.5 py-3">
              <div className="mb-1 text-sm font-semibold">Summary</div>
              <p className="text-sm leading-relaxed text-foreground">{row.notes.summary}</p>
            </div>
          ) : null}

          {sections.map((section) => (
            <div key={section.title}>
              <h3 className="mb-1.5 text-sm font-semibold">{section.title}</h3>
              <ul className="space-y-1">
                {section.items.map((item, index) => (
                  <li
                    key={`${section.title}-${index}`}
                    className="flex gap-2.5 text-sm text-foreground"
                  >
                    <span className="mt-[0.4rem] h-1.5 w-1.5 shrink-0 rounded-full bg-brand-purple/70" />
                    <span className="leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      ) : null}
    </section>
  );
}
