// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const serverEnv = typeof process !== "undefined" ? process.env : {};
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || serverEnv.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || serverEnv.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // KNOWN LIMITATION (SEC-L-002, deferred):
      // Auth tokens live in localStorage. If an XSS bug ever lands, attacker
      // JS can read the access/refresh tokens and replay them. Mitigations
      // already in place that defang the realistic attack:
      //   - strict per-request CSP with nonce + 'strict-dynamic' (server.ts)
      //     blocks inline-injected <script> from executing
      //   - no dangerouslySetInnerHTML on user-supplied content
      //   - X-Frame-Options DENY + frame-ancestors 'none' blocks clickjacking
      //     that could be used to phish tokens
      // The clean fix is migrating to @supabase/ssr with httpOnly cookies
      // and a server-side PKCE exchange. That touches auth-context, the
      // OAuth callback route, server.ts, and every route loader, so it's
      // intentionally deferred until after the MVP. Don't loosen the CSP
      // above without also doing the cookie migration.
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: "pkce",
      // We handle URL code exchange explicitly via exchangeAuthCodeFromUrl()
      // in auth-context.tsx. Disabling the auto path stops a race where both
      // the manual call and Supabase's auto-detection consumed the same
      // one-time `code` param and the loser logged "code already used".
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
